name: Deploy Korean Mappers Map

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'public/data/mappers.json'
      - 'app/**'
      - 'components/**'
      - 'pages/**'
      - 'styles/**'
      - 'next.config.js'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Verify data exists
      run: |
        if [ -f "./public/data/mappers.json" ]; then
          echo "✅ mappers.json found in source directory"
          echo "File size: $(du -h ./public/data/mappers.json | cut -f1)"
          echo "Last modified: $(stat -c %y ./public/data/mappers.json)"
        else
          echo "❌ Error: mappers.json not found in ./public/data/"
          echo "Contents of ./public/data/:"
          ls -la ./public/data/ || echo "./public/data/ directory does not exist"
          exit 1
        fi
      
    - name: Build site
      run: npm run export
      
    - name: Verify data exists in output
      run: |
        if [ -f "./out/data/mappers.json" ]; then
          echo "✅ mappers.json found in output directory"
          echo "File size: $(du -h ./out/data/mappers.json | cut -f1)"
        else
          echo "⚠️ Warning: mappers.json not found in output directory"
          echo "Contents of ./out/data/:"
          ls -la ./out/data/ || echo "./out/data/ directory does not exist"
        fi
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        force_orphan: true
